# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LpVLaOHMKaHQlejGe8kfkwxiYU6V8OV4
"""

import whisper
import re
from PIL import Image
import os
import app
# from IPython.display import display  # Uncomment if running in IPython environment like Jupyter or Colab

# Load the Whisper model
model = whisper.load_model("base")



# Transcribe the audio file
result = model.transcribe("static/audio1.wav")

# Print the transcribed text
print("Transcribed Text:", result["text"])

# Step 1: Create a dictionary to map English alphabets to ISL image paths
alphabet_to_isl_image = {
    'a': '/Users/jayantgoel/PycharmProjects/Indian/A/0.jpg',
    'b': '/Users/jayantgoel/PycharmProjects/Indian/B/1.jpg',
    'c': '/Users/jayantgoel/PycharmProjects/Indian/C/2.jpg',
    'd': '/Users/jayantgoel/PycharmProjects/Indian/D/3.jpg',
    'e': '/Users/jayantgoel/PycharmProjects/Indian/E/4.jpg',
    'f': '/Users/jayantgoel/PycharmProjects/Indian/F/5.jpg',
    'g': '/Users/jayantgoel/PycharmProjects/Indian/G/6.jpg',
    'h': '/Users/jayantgoel/PycharmProjects/Indian/H/7.jpg',
    'i': '/Users/jayantgoel/PycharmProjects/Indian/I/8.jpg',
    'j': '/Users/jayantgoel/PycharmProjects/Indian/J/9.jpg',
    'k': '/Users/jayantgoel/PycharmProjects/Indian/K/10.jpg',
    'l': '/Users/jayantgoel/PycharmProjects/Indian/L/11.jpg',
    'm': '/Users/jayantgoel/PycharmProjects/Indian/M/12.jpg',
    'n': '/Users/jayantgoel/PycharmProjects/Indian/N/13.jpg',
    'o': '/Users/jayantgoel/PycharmProjects/Indian/O/14.jpg',
    'p': '/Users/jayantgoel/PycharmProjects/Indian/P/15.jpg',
    'q': '/Users/jayantgoel/PycharmProjects/Indian/Q/16.jpg',
    'r': '/Users/jayantgoel/PycharmProjects/Indian/R/17.jpg',
    's': '/Users/jayantgoel/PycharmProjects/Indian/S/18.jpg',
    't': '/Users/jayantgoel/PycharmProjects/Indian/T/19.jpg',
    'u': '/Users/jayantgoel/PycharmProjects/Indian/U/20.jpg',
    'v': '/Users/jayantgoel/PycharmProjects/Indian/V/21.jpg',
    'w': '/Users/jayantgoel/PycharmProjects/Indian/W/22.jpg',
    'x': '/Users/jayantgoel/PycharmProjects/Indian/X/23.jpg',
    'y': '/Users/jayantgoel/PycharmProjects/Indian/Y/24.jpg',
    'z': '/Users/jayantgoel/PycharmProjects/Indian/Z/25.jpg',
    ' ': '/Users/jayantgoel/PycharmProjects/SIH/static/Image.jpg'
    # Add paths for all alphabet letters
}

# Function to check if a file exists
def file_exists(filepath):
    return os.path.isfile(filepath)

# Step 2: Function to preprocess text by removing punctuation and tokenizing into words
def preprocess_text_to_words(sentence):
    # Remove punctuation marks
    sentence = re.sub(r'[^\w\s]', '', sentence)
    # Convert to lowercase for consistency
    sentence = sentence.lower()
    # Split the sentence into words
    return sentence.split()

# Step 3: Function to preprocess each word into letters
def preprocess_word_to_letters(word):
    return list(word)

# Step 4: Function to preprocess text by removing punctuation and tokenizing into letters
def preprocess_text_to_letters(sentence):
    # Remove punctuation marks
    sentence = re.sub(r'[^\w\s]', '', sentence)
    # Convert to lowercase for consistency
    sentence = sentence.lower()
    # Remove spaces and return list of letters
    return list(sentence)

def map_to_isl(letters):
    # Initialize a list to hold the ISL image paths
    isl_image_paths = []

    for letter in letters:
        # If the letter is a space, skip it

        # Add the ISL image path corresponding to the letter
        isl_image_paths.append(alphabet_to_isl_image.get(letter, '/content/default_image.jpg'))

    return isl_image_paths

def display_images_in_one_window(image_paths):
    # Initialize a list to hold the loaded images
    images = []

    # Load images based on the image_paths list
    for path in image_paths:
        if file_exists(path):
            try:
                img = Image.open(path)
                images.append(img)
            except Exception as e:
                print(f"Error loading image {path}: {e}")
        else:
            print(f"File not found: {path}")

    if not images:
        print("No images loaded.")
        return

    # Get the width and height of each image
    widths, heights = zip(*(img.size for img in images))

    # Create a blank canvas large enough to hold all the images in a row
    total_width = sum(widths)
    max_height = max(heights)

    # Create a blank image (canvas) to hold all images
    combined_image = Image.new('RGB', (total_width, max_height))

    # Paste each image onto the blank canvas sequentially
    x_offset = 0
    for img in images:
        combined_image.paste(img, (x_offset, 0))
        x_offset += img.width  # Move the x_offset to the right for the next image

    # Display the combined image in Colab
    combined_image.save('static/output.jpg')

# Step 7: Putting everything together
def convert_text_to_isl(sentence):
    # Preprocess the sentence into letters
    letters = preprocess_text_to_letters(sentence)

    # Map the letters to corresponding ISL images
    isl_images = map_to_isl(letters)

    # Display all the ISL images in one window
    display_images_in_one_window(isl_images)

# Example usage
# input_text = input("Enter a sentence: ")
convert_text_to_isl(result["text"])
